
sharding.jdbc.datasource.names: master0,master1,master0slave0,master1slave0

sharding.jdbc.datasource.master0.type: com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.master0.driver-class-name: com.mysql.jdbc.Driver
sharding.jdbc.datasource.master0.url: jdbc:mysql://localhost:3306/cool?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
sharding.jdbc.datasource.master0.username: root
sharding.jdbc.datasource.master0.password: root

sharding.jdbc.datasource.master0slave0.type: com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.master0slave0.driver-class-name: com.mysql.jdbc.Driver
sharding.jdbc.datasource.master0slave0.url: jdbc:mysql://192.168.0.7:3306/cool?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
sharding.jdbc.datasource.master0slave0.username: root
sharding.jdbc.datasource.master0slave0.password: wswx_acc


sharding.jdbc.datasource.master1.type: com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.master1.driver-class-name: com.mysql.jdbc.Driver
sharding.jdbc.datasource.master1.url: jdbc:mysql://localhost:3306/cool2?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
sharding.jdbc.datasource.master1.username: root
sharding.jdbc.datasource.master1.password: root

sharding.jdbc.datasource.master1slave0.type: com.alibaba.druid.pool.DruidDataSource
sharding.jdbc.datasource.master1slave0.driver-class-name: com.mysql.jdbc.Driver
sharding.jdbc.datasource.master1slave0.url: jdbc:mysql://192.168.0.7:3306/cool2?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
sharding.jdbc.datasource.master1slave0.username: root
sharding.jdbc.datasource.master1slave0.password:  wswx_acc

sharding.jdbc.config.sharding.default-database-strategy.inline.sharding-column: count
sharding.jdbc.config.sharding.default-database-strategy.inline.algorithm-expression: master$->{count % 2}

sharding.jdbc.config.sharding.tables.user.actual-data-nodes: ds$->{0..1}.user_$->{0..4}
sharding.jdbc.config.sharding.tables.user.table-strategy.inline.sharding-column: count
sharding.jdbc.config.sharding.tables.user.table-strategy.inline.algorithm-expression: user_$->{count % 5}
sharding.jdbc.config.sharding.tables.user.key-generator-column-name: id

#sharding.jdbc.config.sharding.binding-tables: user




sharding.jdbc.config.sharding.master-slave-rules.ds0.master-data-source-name: master0
sharding.jdbc.config.sharding.master-slave-rules.ds0.slave-data-source-names: master0slave0
sharding.jdbc.config.sharding.master-slave-rules.ds1.master-data-source-name: master1
sharding.jdbc.config.sharding.master-slave-rules.ds1.slave-data-source-names: master1slave0

